// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CIcon: typeof import('./../components/cIcon/index.vue')['default']
    Draggable: typeof import('./../components/draggable/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    IconChooseSrc: typeof import('./../components/iconChoose/src/index.vue')['default']
    NDialogSrc: typeof import('./../components/nDialog/src/index.vue')['default']
    NEditorSrc: typeof import('./../components/nEditor/src/index.vue')['default']
    NFormSrc: typeof import('./../components/nForm/src/index.vue')['default']
    NModelFormSrc: typeof import('./../components/nModelForm/src/index.vue')['default']
    NTableSrc: typeof import('./../components/nTable/src/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
